/* Generated by Yosys 0.62+9 (git sha1 1717fa018, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "./rtl/overlapping_mo_101.sv:1.1-31.10" *)
module overlap_mo_101(clk, arstn, in, out);
  (* src = "./rtl/overlapping_mo_101.sv:2.18-2.21" *)
  input clk;
  wire clk;
  (* src = "./rtl/overlapping_mo_101.sv:2.24-2.29" *)
  input arstn;
  wire arstn;
  (* src = "./rtl/overlapping_mo_101.sv:2.32-2.34" *)
  input in;
  wire in;
  (* src = "./rtl/overlapping_mo_101.sv:3.18-3.21" *)
  output out;
  wire out;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* force_downto = 32'd1 *)
  (* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:579.28-579.29" *)
  wire [5:0] _09_;
  (* force_downto = 32'd1 *)
  (* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:591.28-591.35" *)
  wire [5:0] _10_;
  (* force_downto = 32'd1 *)
  (* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:581.22-581.23" *)
  wire [2:0] _11_;
  (* force_downto = 32'd1 *)
  (* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:586.19-586.22" *)
  wire [1:0] _12_;
  (* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:605.13-605.15" *)
  wire _13_;
  (* enum_type = "$enum0" *)
  (* enum_value_00 = "\\S0" *)
  (* enum_value_01 = "\\S1" *)
  (* enum_value_10 = "\\S2" *)
  (* enum_value_11 = "\\S3" *)
  (* src = "./rtl/overlapping_mo_101.sv:8.9-8.22" *)
  (* wiretype = "\\state_t" *)
  reg [1:0] current_state;
  (* enum_type = "$enum0" *)
  (* enum_value_00 = "\\S0" *)
  (* enum_value_01 = "\\S1" *)
  (* enum_value_10 = "\\S2" *)
  (* enum_value_11 = "\\S3" *)
  (* src = "./rtl/overlapping_mo_101.sv:8.25-8.35" *)
  (* wiretype = "\\state_t" *)
  wire [1:0] next_state;
  (* \always_ff  = 32'd1 *)
  (* src = "./rtl/overlapping_mo_101.sv:10.1-15.4" *)
  always_ff @(posedge clk, negedge arstn)
    if (!arstn) current_state[0] <= 1'h0;
    else current_state[0] <= next_state[0];
  (* \always_ff  = 32'd1 *)
  (* src = "./rtl/overlapping_mo_101.sv:10.1-15.4" *)
  always_ff @(posedge clk, negedge arstn)
    if (!arstn) current_state[1] <= 1'h0;
    else current_state[1] <= next_state[1];
  assign _00_ = ~current_state[1];
  assign _01_ = ~current_state[0];
  assign _10_[4] = in &(* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:593.44-593.84" *)  _11_[2];
  assign _10_[2] = in &(* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:593.44-593.84" *)  _11_[1];
  assign _10_[0] = in &(* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:593.44-593.84" *)  _11_[0];
  assign _10_[1] = _09_[1] &(* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:593.44-593.84" *)  _11_[0];
  assign _05_ = _01_ |(* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12" *)  _00_;
  assign _06_ = current_state[0] |(* src = "./rtl/overlapping_mo_101.sv:21.42-21.42|./rtl/overlapping_mo_101.sv:19.5-25.12" *)  _00_;
  assign _07_ = _01_ |(* src = "./rtl/overlapping_mo_101.sv:20.42-20.42|./rtl/overlapping_mo_101.sv:19.5-25.12" *)  current_state[1];
  assign _12_[1] = _10_[1] |(* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:601.20-601.31" *)  _10_[2];
  assign _02_ = _10_[0] |(* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:601.20-601.31" *)  _10_[2];
  assign _12_[0] = _02_ |(* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:601.20-601.31" *)  _10_[4];
  assign _03_ = _11_[0] |(* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:605.13-605.15" *)  _11_[1];
  assign _13_ = _03_ |(* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:605.13-605.15" *)  _11_[2];
  assign _11_[0] = out | _08_;
  assign _04_ = current_state[0] |(* src = "./rtl/overlapping_mo_101.sv:19.24-19.24|./rtl/overlapping_mo_101.sv:19.5-25.12" *)  current_state[1];
  assign out = ~(* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12" *) _05_;
  assign _11_[1] = ~(* src = "./rtl/overlapping_mo_101.sv:21.42-21.42|./rtl/overlapping_mo_101.sv:19.5-25.12" *) _06_;
  assign _08_ = ~(* src = "./rtl/overlapping_mo_101.sv:20.42-20.42|./rtl/overlapping_mo_101.sv:19.5-25.12" *) _07_;
  assign _11_[2] = ~(* src = "./rtl/overlapping_mo_101.sv:19.24-19.24|./rtl/overlapping_mo_101.sv:19.5-25.12" *) _04_;
  assign _09_[1] = ~(* src = "./rtl/overlapping_mo_101.sv:23.27-23.40" *) in;
  assign next_state[0] = _13_ ? (* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:605.13-605.25" *) _12_[0] : 1'hx;
  assign next_state[1] = _13_ ? (* src = "./rtl/overlapping_mo_101.sv:22.42-22.42|./rtl/overlapping_mo_101.sv:19.5-25.12|/home/mohamedahmed/Utils/oss-cad-suite/lib/../share/yosys/techmap.v:605.13-605.25" *) _12_[1] : 1'hx;
  assign { _10_[5], _10_[3] } = { 1'h0, _10_[2] };
  assign { _09_[5:2], _09_[0] } = { 1'h0, in, in, in, in };
endmodule
